"""Offline English -> Hindi rendering for trial titles, criteria and reasons.

The results UI and the Excel export already translated *labels* (column
headers, verdict names); this module extends coverage to the *content* itself:
trial titles, inclusion/exclusion criteria, and the rule engine's reason
strings - without depending on the frequently rate-limited Groq API.

It is deliberately a *medical domain* glossary, not general machine
translation - the mirror image of services/hi_lexicon.py (which converts
Hindi clinical notes to English for the NER). Three passes:

1. regex TEMPLATES for the sentence shapes this data actually uses (numeric
   comparisons, age ranges, durations, "history of X", "diagnosed with X") -
   these re-order numbers and direction words into natural Hindi
   postpositions ("45 से कम", "X का इतिहास");
2. multi-word PHRASES (diseases, drugs, trial-design boilerplate), longest
   first;
3. single WORDS - the remaining medical vocabulary plus a few glue words
   (and/or/not). Unmapped tokens pass through unchanged, so units (mg/dL),
   abbreviations (HbA1c, eGFR, BMI, ULN) and rare drug names survive - the
   same "Latin survives" rule hi_lexicon.py applies in reverse. Untranslated
   English glue reads as natural clinical Hinglish.
"""
from __future__ import annotations

import re
from functools import lru_cache

# ---------------------------------------------------------------------------
# 1) Sentence-shape templates (applied first, case-insensitive)
# ---------------------------------------------------------------------------

# Optional unit that may follow a number ("7.5 percent", "45 mg", "6 months") -
# CAPTURED so templates can re-position it in the Hindi word order.
_UNIT_CAP = r"(years?|months?|weeks?|days?|hours?|percent|%|mg|ml|kg|mmhg|units?)?"

# Stop lookahead: capture ends at punctuation or a clause boundary word.
_STOP = (r"(?=\s*(?:[.;,]|$|\band\b|\bor\b|\bwith\b|\bwithout\b|\bwho\b|"
         r"\bwhich\b|\bthat\b|\bwhile\b|\bduring\b|\bdespite\b|\bunless\b|"
         r"\brequiring\b|\bnot\b|\bwithin\b|\bif\b))")

_TEMPLATES: list[tuple[re.Pattern, str]] = [
    # --- numeric comparisons -> Hindi postpositions -------------------------
    (re.compile(r"\bgreater than or equal to\s+(\d+(?:\.\d+)?)\s*" + _UNIT_CAP, re.I),
     r"\1 \2 से अधिक या बराबर "),
    (re.compile(r"\bless than or equal to\s+(\d+(?:\.\d+)?)\s*" + _UNIT_CAP, re.I),
     r"\1 \2 से कम या बराबर "),
    (re.compile(r"\bno more than\s+(\d+(?:\.\d+)?)\s*" + _UNIT_CAP, re.I),
     r"अधिक से अधिक \1 \2 "),
    (re.compile(r"\b(?:greater than|more than|above|over)\s+(\d+(?:\.\d+)?)\s*" + _UNIT_CAP, re.I),
     r"\1 \2 से अधिक "),
    (re.compile(r"\b(?:less than|below|under)\s+(\d+(?:\.\d+)?)\s*" + _UNIT_CAP, re.I),
     r"\1 \2 से कम "),
    (re.compile(r"\bbetween\s+(\d+(?:\.\d+)?)\s*(?:and|to)\s+(\d+(?:\.\d+)?)\s*" + _UNIT_CAP, re.I),
     r"\1 और \2 \3 के बीच "),
    (re.compile(r"\bat least\s+(\d+(?:\.\d+)?)\s*" + _UNIT_CAP, re.I),
     r"कम से कम \1 \2 "),
    (re.compile(r"\bup to\s+(\d+(?:\.\d+)?)\s*" + _UNIT_CAP, re.I),
     r"\1 \2 तक "),
    # --- ages ----------------------------------------------------------------
    (re.compile(r"\b(?:aged|age)\s+(\d+)\s*(?:-|to|–)\s*(\d+)(?:\s*years?)?\b", re.I),
     r"आयु \1-\2 वर्ष"),
    (re.compile(r"\b(\d+)\s*(?:-|to|–)\s*(\d+)\s*years?\s+of\s+age\b", re.I),
     r"\1-\2 वर्ष की आयु"),
    (re.compile(r"\b(\d+)\s+years?\s+of\s+age\b", re.I),
     r"\1 वर्ष की आयु"),
    (re.compile(r"\baged\s+(?:over|above|at least)\s+(\d+)\s*years?\b", re.I),
     r"आयु \1 वर्ष से अधिक"),
    (re.compile(r"\bage\s+(?:of\s+)?(\d+)\s+years?\s+or\s+(?:older|more)\b", re.I),
     r"आयु \1 वर्ष या अधिक"),
    # --- "history of X (within past N units)" -> time first, then possession -
    (re.compile(r"\bno\s+(?:known\s+)?history\s+of\s+([A-Za-z][\w ,/()-]{1,60}?)"
                r"\s+within\s+(?:the\s+)?(?:past\s+|last\s+)?(\d+)\s*(years?|months?|weeks?|days?)\b", re.I),
     r"पिछले \2 \3 में \1 का कोई इतिहास नहीं"),
    (re.compile(r"\bhistory\s+of\s+([A-Za-z][\w ,/()-]{1,60}?)"
                r"\s+within\s+(?:the\s+)?(?:past\s+|last\s+)?(\d+)\s*(years?|months?|weeks?|days?)\b", re.I),
     r"पिछले \2 \3 में \1 का इतिहास"),
    (re.compile(r"\bwithin\s+(?:the\s+)?(?:past\s+|last\s+)?(\d+)\s*(years?|months?|weeks?|days?|hours?)\b", re.I),
     r"पिछले \1 \2 में"),
    # --- diagnosis timing -----------------------------------------------------
    (re.compile(r"\bdiagnosed\s+at\s+least\s+(\d+)\s*(years?|months?|weeks?|days?)\s+ago\b", re.I),
     r"कम से कम \1 \2 पहले निदान"),
    (re.compile(r"\bnewly\s+diagnosed\s+within\s+(?:the\s+)?(?:past\s+|last\s+)?"
                r"(\d+)\s*(years?|months?|weeks?|days?)\b", re.I),
     r"पिछले \1 \2 में नया निदान"),
    # --- negated histories / prior treatment ---------------------------------
    (re.compile(r"\bno\s+(?:known\s+)?history\s+of\s+([A-Za-z][\w ,/()-]{1,60}?)" + _STOP, re.I),
     r"\1 का कोई इतिहास नहीं"),
    (re.compile(r"\bhistory\s+of\s+([A-Za-z][\w ,/()-]{1,60}?)" + _STOP, re.I),
     r"\1 का इतिहास"),
    (re.compile(r"\bno\s+previous\s+treatment\s+with\s+([A-Za-z][\w ,/()-]{1,40}?)" + _STOP, re.I),
     r"\1 का पहले कोई इलाज नहीं"),
    (re.compile(r"\bnot\s+previously\s+treated\s+with\s+([A-Za-z][\w ,/()-]{1,40}?)" + _STOP, re.I),
     r"\1 का पहले कोई इलाज नहीं"),
    (re.compile(r"\bnever\s+received\s+([A-Za-z][\w ,/()-]{1,40}?)" + _STOP, re.I),
     r"\1 कभी नहीं लिया"),
    (re.compile(r"\bcurrent\s+use\s+of\s+([A-Za-z][\w ,/()-]{1,40}?)" + _STOP, re.I),
     r"\1 का वर्तमान उपयोग"),
    (re.compile(r"\bdiagnosed\s+with\s+([A-Za-z][\w ,/()-]{1,60}?)" + _STOP, re.I),
     r"\1 का निदान"),
    # --- attachment postpositions (bounded captures) --------------------------
    (re.compile(r"\bwithout\s+([A-Za-z][\w ,/()-]{1,50}?)" + _STOP, re.I),
     r"\1 के बिना"),
    (re.compile(r"\bwith\s+([A-Za-z][\w ,/()-]{1,50}?)" + _STOP, re.I),
     r"\1 के साथ"),
]

# ---------------------------------------------------------------------------
# 2) Multi-word phrases (longest first; hyphen/space treated as equivalent)
# ---------------------------------------------------------------------------

_PHRASES: dict[str, str] = {
    # --- criterion boilerplate ------------------------------------------------
    "key inclusion criteria": "मुख्य समावेशन मानदंड",
    "key exclusion criteria": "मुख्य अपवर्जन मानदंड",
    "main inclusion criteria": "मुख्य समावेशन मानदंड",
    "inclusion criteria": "समावेशन मानदंड",
    "exclusion criteria": "अपवर्जन मानदंड",
    "inclusion criterion": "समावेशन मानदंड",
    "exclusion criterion": "अपवर्जन मानदंड",
    "potential exclusion": "संभावित अपवर्जन",
    "analysis failed": "विश्लेषण असफल",
    "upper limit of normal": "सामान्य की ऊपरी सीमा",
    "lower limit of normal": "सामान्य की निचली सीमा",
    # --- rule-engine reason phrases -------------------------------------------
    "is within the required range": "आवश्यक सीमा के भीतर है",
    "is below the trial minimum": "ट्रायल की न्यूनतम सीमा से कम है",
    "is above the trial maximum": "ट्रायल की अधिकतम सीमा से अधिक है",
    "does not satisfy inclusion criterion": "समावेशन मानदंड को संतुष्ट नहीं करता",
    "satisfies inclusion criterion": "समावेशन मानदंड को संतुष्ट करता",
    "does not trigger exclusion": "अपवर्जन को ट्रिगर नहीं करता",
    "trial excludes patients where": "ट्रायल उन मरीज़ों को अपवर्जित करता है जहां",
    "trial excludes": "ट्रायल अपवर्जित करता है",
    "trial requires patients on": "ट्रायल उन मरीज़ों की मांग करता है जो",
    "trial requires": "ट्रायल मांग करता है",
    "trial targets patients": "ट्रायल ऐसे मरीज़ों को लक्षित करता है",
    "no conflict with": "से कोई टकराव नहीं",
    "does not match": "से मेल नहीं खाती",
    "matches trial condition": "ट्रायल की बीमारी से मेल खाती",
    "matches the condition": "बीमारी से मेल खाती",
    "patient condition": "मरीज़ की बीमारी",
    "trial condition": "ट्रायल की बीमारी",
    "studied by this trial": "जिस बीमारी का यह ट्रायल अध्ययन करता है",
    "medical history records": "चिकित्सा इतिहास में दर्ज है",
    "medical history shows": "चिकित्सा इतिहास दिखाता है",
    "disease duration": "बीमारी की अवधि",
    "current medication list": "वर्तमान दवा सूची",
    "medication history": "दवा का इतिहास",
    "previous treatment status": "पिछले इलाज की स्थिति",
    "patient is on": "मरीज़ पर है",
    "patient is a healthy volunteer": "मरीज़ एक स्वस्थ स्वयंसेवक है",
    "patient has": "मरीज़ में है",
    "patient age": "मरीज़ की उम्र",
    "patient gender": "मरीज़ का लिंग",
    "gender criterion satisfied": "लिंग मानदंड पूरा हुआ",
    "trial accepts": "ट्रायल स्वीकार करता है",
    "participants only": "प्रतिभागियों को ही",
    "healthy volunteer": "स्वस्थ स्वयंसेवक",
    "normal volunteer": "स्वस्थ स्वयंसेवक",
    "healthy adult": "स्वस्थ वयस्क",
    "healthy subject": "स्वस्थ प्रतिभागी",
    # --- demographics / consent ------------------------------------------------
    "either sex": "कोई भी लिंग",
    "both sexes": "दोनों लिंग",
    "both genders": "दोनों लिंग",
    "male or female": "पुरुष या महिला",
    "of childbearing potential": "प्रजनन क्षमता वाली",
    "childbearing potential": "प्रजनन क्षमता",
    "medically stable": "चिकित्सकीय रूप से स्थिर",
    "able to comply": "पालन करने में सक्षम",
    "able and willing": "सक्षम और इच्छुक",
    "written informed consent": "लिखित सूचित सहमति",
    "informed consent": "सूचित सहमति",
    "performance status": "परफॉर्मेंस स्टेटस",
    "pregnant or breastfeeding women": "गर्भवती या स्तनपान कराने वाली महिलाएं",
    "pregnant or lactating women": "गर्भवती या धात्री महिलाएं",
    "breastfeeding women": "स्तनपान कराने वाली महिलाएं",
    "lactating women": "धात्री महिलाएं",
    "not pregnant": "गर्भवती नहीं",
    "years of age": "वर्ष की आयु",
    "body mass index": "बॉडी मास इंडेक्स",
    "moderate to severe": "मध्यम से गंभीर",
    "mild to moderate": "हल्का से मध्यम",
    "moderate or severe": "मध्यम या गंभीर",
    # --- cardiovascular ---------------------------------------------------------
    "congestive heart failure": "कंजेस्टिव हृदय विफलता",
    "heart failure": "हृदय विफलता",
    "post myocardial infarction": "हार्ट अटैक के बाद",
    "myocardial infarction": "हार्ट अटैक",
    "coronary artery disease": "कोरोनरी धमनी रोग",
    "coronary heart disease": "कोरोनरी हृदय रोग",
    "acute coronary syndrome": "तीव्र कोरोनरी सिंड्रोम",
    "atrial fibrillation": "अलिंद फिब्रिलेशन",
    "preserved ejection fraction": "संरक्षित इजेक्शन फ्रैक्शन",
    "reduced ejection fraction": "कम इजेक्शन फ्रैक्शन",
    "ventricular ejection fraction": "वेंट्रिकल इजेक्शन फ्रैक्शन",
    "ejection fraction": "इजेक्शन फ्रैक्शन",
    "left ventricular": "बाएं वेंट्रिकल",
    "cardiac arrest": "हृदय गति रुकना",
    "cardiac surgery": "हृदय सर्जरी",
    "cerebrovascular accident": "स्ट्रोक",
    "transient ischemic attack": "ट्रांज़िएंट इस्कीमिक अटैक",
    "peripheral artery disease": "पेरिफेरल धमनी रोग",
    "peripheral arterial disease": "पेरिफेरल धमनी रोग",
    "deep vein thrombosis": "गहरी शिरा थ्रॉम्बोसिस",
    "pulmonary embolism": "फुफ्फुसीय एम्बोलिज़्म",
    "venous thromboembolism": "वेनस थ्रॉम्बोएम्बोलिज़्म",
    "high blood pressure": "उच्च रक्तचाप",
    "uncontrolled hypertension": "अनियंत्रित उच्च रक्तचाप",
    "uncontrolled blood pressure": "अनियंत्रित रक्तचाप",
    "secondary hypertension": "द्वितीयक उच्च रक्तचाप",
    "portal hypertension": "पोर्टल उच्च रक्तचाप",
    "pulmonary arterial hypertension": "फुफ्फुसीय धमनी उच्च रक्तचाप",
    "blood pressure": "रक्तचाप",
    "fasting plasma glucose": "खाली पेट ग्लूकोज",
    "fasting glucose": "खाली पेट ग्लूकोज",
    # --- diabetes ---------------------------------------------------------------
    "type 2 diabetes mellitus": "टाइप 2 मधुमेह",
    "type 1 diabetes mellitus": "टाइप 1 मधुमेह",
    "type 2 diabetes": "टाइप 2 मधुमेह",
    "type 1 diabetes": "टाइप 1 मधुमेह",
    "diabetes mellitus": "मधुमेह",
    "gestational diabetes": "गर्भकालीन मधुमेह",
    "diabetic ketoacidosis": "मधुमेह कीटोएसिडोसिस",
    "diabetic nephropathy": "मधुमेह नेफ्रोपैथी",
    "diabetic retinopathy": "मधुमेह रेटिनोपैथी",
    "diabetic foot ulcer": "मधुमेह फुट अल्सर",
    "impaired fasting glucose": "बिगड़ा खाली पेट ग्लूकोज",
    "impaired glucose tolerance": "बिगड़ी ग्लूकोज सहनशीलता",
    # --- kidney / liver ----------------------------------------------------------
    "chronic kidney disease": "पुरानी किडनी बीमारी",
    "polycystic kidney disease": "पॉलीसिस्टिक किडनी बीमारी",
    "end stage renal disease": "अंतिम चरण किडनी बीमारी",
    "kidney disease": "किडनी बीमारी",
    "kidney function": "किडनी फंक्शन",
    "impaired kidney function": "खराब किडनी फंक्शन",
    "renal impairment": "किडनी की शिथिलता",
    "renal insufficiency": "किडनी की कमी",
    "renal failure": "किडनी फेल",
    "iga nephropathy": "आईजीए नेफ्रोपैथी",
    "chronic liver disease": "पुराना यकृत रोग",
    "liver disease": "यकृत रोग",
    "liver function": "यकृत फंक्शन",
    "hepatic impairment": "यकृत की शिथिलता",
    "hepatic failure": "यकृत फेल",
    "decompensated cirrhosis": "डीकंपेंसेटेड सिरोसिस",
    "compensated cirrhosis": "कंपेंसेटेड सिरोसिस",
    "hepatitis b": "हेपेटाइटिस बी",
    "hepatitis c": "हेपेटाइटिस सी",
    "nonalcoholic steatohepatitis": "नॉन-अल्कोहलिक स्टीटोहेपेटाइटिस",
    "metabolic dysfunction associated steatohepatitis": "मेटाबॉलिक स्टीटोहेपेटाइटिस",
    "metabolic dysfunction associated": "मेटाबॉलिक डिसफंक्शन से जुड़ा",
    "steatotic liver disease": "स्टीटोटिक लिवर रोग",
    "non alcoholic fatty liver disease": "नॉन-अल्कोहलिक फैटी लिवर रोग",
    "nonalcoholic fatty liver disease": "नॉन-अल्कोहलिक फैटी लिवर रोग",
    "fatty liver disease": "फैटी लिवर रोग",
    "fatty liver": "फैटी लिवर",
    "gall bladder cancer": "पित्ताशय का कैंसर",
    # --- cancer ------------------------------------------------------------------
    "advanced breast cancer": "उन्नत स्तन कैंसर",
    "metastatic breast cancer": "मेटास्टैटिक स्तन कैंसर",
    "early breast cancer": "प्रारंभिक स्तन कैंसर",
    "breast cancer": "स्तन कैंसर",
    "breast neoplasms": "स्तन के ट्यूमर",
    "non small cell lung cancer": "नॉन-स्मॉल सेल फेफड़ों का कैंसर",
    "small cell lung cancer": "स्मॉल सेल फेफड़ों का कैंसर",
    "lung cancer": "फेफड़ों का कैंसर",
    "colorectal cancer": "कोलोरेक्टल कैंसर",
    "pancreatic cancer": "अग्न्याशय कैंसर",
    "prostate cancer": "प्रोस्टेट कैंसर",
    "ovarian cancer": "अंडाशय का कैंसर",
    "gastric cancer": "पेट का कैंसर",
    "head and neck cancer": "सिर और गर्दन का कैंसर",
    "solid tumor": "ठोस ट्यूमर",
    "solid tumour": "ठोस ट्यूमर",
    "hematologic malignancy": "रक्त कैंसर",
    "haematologic malignancy": "रक्त कैंसर",
    "acute myeloid leukemia": "तीव्र मायलॉइड ल्यूकीमिया",
    "acute myeloid leukaemia": "तीव्र मायलॉइड ल्यूकीमिया",
    "myelodysplastic syndrome": "मायलोडिसप्लास्टिक सिंड्रोम",
    "myelodysplastic syndromes": "मायलोडिसप्लास्टिक सिंड्रोम",
    "sickle cell disease": "सिकल सेल रोग",
    "sickle cell": "सिकल सेल",
    "paroxysmal nocturnal hemoglobinuria": "पैरोक्सिज़्मल नॉक्टर्नल हीमोग्लोबिन्यूरिया",
    # --- respiratory --------------------------------------------------------------
    "chronic obstructive pulmonary disease": "पुरानी अवरोधक फुफ्फुसीय बीमारी",
    "chronic obstructive": "पुरानी अवरोधक",
    "idiopathic pulmonary fibrosis": "इडियोपैथिक फुफ्फुसीय फाइब्रोसिस",
    "pulmonary fibrosis": "फुफ्फुसीय फाइब्रोसिस",
    "obstructive sleep apnea": "ऑब्सट्रक्टिव स्लीप एपनिया",
    "sleep apnea": "स्लीप एपनिया",
    "cystic fibrosis": "सिस्टिक फाइब्रोसिस",
    "severe asthma": "गंभीर दमा",
    "uncontrolled asthma": "अनियंत्रित दमा",
    "mild asthma": "हल्का दमा",
    "acute exacerbation": "तीव्र बिगड़न (एक्सेर्बेशन)",
    "continuous glucose monitoring": "निरंतर ग्लूकोज निगरानी",
    "glucose monitoring": "ग्लूकोज निगरानी",
    # --- rheum / autoimmune / other ------------------------------------------------
    "rheumatoid arthritis": "रूमेटाइड गठिया",
    "psoriatic arthritis": "सोरायसिस गठिया",
    "ankylosing spondylitis": "एंकायलोज़िंग स्पोंडिलाइटिस",
    "systemic lupus erythematosus": "सिस्टमिक लूपस",
    "autoimmune disease": "ऑटोइम्यून बीमारी",
    "depressive disorder": "अवसाद विकार",
    "major depressive disorder": "गंभीर अवसाद विकार",
    "generalized anxiety disorder": "सामान्यीकृत चिंता विकार",
    "bipolar disorder": "बाइपोलर विकार",
    "post traumatic stress disorder": "पोस्ट ट्रॉमैटिक स्ट्रेस डिसऑर्डर",
    "multiple sclerosis": "मल्टीपल स्क्लेरोसिस",
    "crohn's disease": "क्रोहन रोग",
    "crohns disease": "क्रोहन रोग",
    "ulcerative colitis": "अल्सरेटिव कोलाइटिस",
    "irritable bowel syndrome": "इरिटेबल बाउल सिंड्रोम",
    "gastroesophageal reflux": "गैस्ट्रोएसोफेजियल रिफ्लक्स",
    "peptic ulcer": "पेप्टिक अल्सर",
    "celiac disease": "सीलियाक रोग",
    "primary open angle glaucoma": "प्राथमिक ओपन एंगल ग्लूकोमा",
    "benign prostatic hyperplasia": "प्रोस्टेट बढ़ना (बीपीएच)",
    "erectile dysfunction": "इरेक्टाइल डिसफंक्शन",
    "overactive bladder": "ओवरएक्टिव ब्लैडर",
    "urinary tract infection": "मूत्र मार्ग संक्रमण",
    "chronic spontaneous urticaria": "पुरानी पित्ती",
    "atopic dermatitis": "एटोपिक डर्मेटाइटिस",
    "polycystic ovary syndrome": "पीसीओएस",
    "vulvovaginal candidiasis": "वल्वोवजाइनल कैंडिडियासिस",
    "anemia in pregnancy": "गर्भावस्था में एनीमिया",
    "anaemia in pregnancy": "गर्भावस्था में एनीमिया",
    "iron deficiency anemia": "आयरन की कमी वाला एनीमिया",
    "iron deficiency anaemia": "आयरन की कमी वाला एनीमिया",
    "hiv infection": "एचआईवी संक्रमण",
    "human immunodeficiency virus": "एचआईवी",
    "latent tuberculosis": "लेटेंट टीबी",
    "neuropathic pain": "न्यूरोपैथिक दर्द",
    "chronic pain": "पुराना दर्द",
    "morbid obesity": "गंभीर मोटापा",
    "obesity or overweight": "मोटापा या अधिक वजन",
    "rituximab treated conditions": "रिटुक्सिमाब से इलाज वाली बीमारियां",
    "hypercholesterolemia": "उच्च कोलेस्ट्रॉल",
    "hypertriglyceridemia": "उच्च ट्राइग्लिसराइड",
    "hyperlipidemia": "हाइपरलिपिडीमिया",
    "dyslipidemia": "डिस्लिपिडीमिया",
    "hyperuricemia": "उच्च यूरिक एसिड",
    "hyperkalemia": "उच्च पोटैशियम",
    "hypokalemia": "कम पोटैशियम",
    "hypoglycemia": "लो ब्लड शुगर",
    "hyperglycemia": "हाई ब्लड शुगर",
    # --- drugs (frequent in trials + Indian practice; rare ones pass through) ------
    "fixed dose combination": "निश्चित खुराक संयोजन",
    "insulin glargine": "ग्लार्जिन इंसुलिन",
    "sglt2 inhibitor": "एसजीएलटी2 इनहिबिटर",
    "sglt2 inhibitors": "एसजीएलटी2 इनहिबिटर",
    "ace inhibitor": "एसीई इनहिबिटर",
    "ace inhibitors": "एसीई इनहिबिटर",
    "angiotensin receptor blocker": "एआरबी",
    "beta blocker": "बीटा ब्लॉकर",
    "beta blockers": "बीटा ब्लॉकर",
    "calcium channel blocker": "कैल्शियम चैनल ब्लॉकर",
    "statin therapy": "स्टैटिन थेरेपी",
    "hydroxychloroquine": "हाइड्रॉक्सीक्लोरोक्वीन",
    "metformin": "मेटफॉर्मिन",
    "insulin": "इंसुलिन",
    "glimepiride": "ग्लिमेपिराइड",
    "sulfonylurea": "सल्फोनिलयूरिया",
    "sitagliptin": "सिटाग्लिप्टिन",
    "vildagliptin": "विल्डाग्लिप्टिन",
    "dapagliflozin": "डापाग्लिफ्लोज़िन",
    "empagliflozin": "एम्पाग्लिफ्लोज़िन",
    "ertugliflozin": "एर्टुग्लिफ्लोज़िन",
    "canagliflozin": "कैनाग्लिफ्लोज़िन",
    "liraglutide": "लिराग्लूटाइड",
    "semaglutide": "सेमाग्लूटाइड",
    "pioglitazone": "पायोग्लिटाज़ोन",
    "acarbose": "एकार्बोज़",
    "repaglinide": "रेपाग्लिनाइड",
    "methotrexate": "मेथोट्रेक्सेट",
    "amlodipine": "एम्लोडिपिन",
    "telmisartan": "टेल्मिसर्टन",
    "losartan": "लोसार्टन",
    "valsartan": "वाल्सार्टन",
    "ramipril": "रामिप्रिल",
    "enalapril": "एनालाप्रिल",
    "lisinopril": "लिसिनोप्रिल",
    "perindopril": "पेरिंडोप्रिल",
    "indapamide": "इंडापामाइड",
    "hydrochlorothiazide": "हाइड्रोक्लोरोथायाज़ाइड",
    "furosemide": "फ्यूरोसेमाइड",
    "torsemide": "टोरसेमाइड",
    "spironolactone": "स्पिरोनोलैक्टोन",
    "bisoprolol": "बिसोप्रोलोल",
    "metoprolol": "मेटोप्रोलोल",
    "carvedilol": "कार्वेडिलोल",
    "nebivolol": "नेबिवोलोल",
    "atenolol": "एटेनोलोल",
    "sacubitril": "सैक्यूबिट्रिल",
    "ivabradine": "इवाब्राडिन",
    "digoxin": "डिगॉक्सिन",
    "amiodarone": "अमियोडारोन",
    "atorvastatin": "एटोर्वास्टैटिन",
    "rosuvastatin": "रोसुवास्टैटिन",
    "simvastatin": "सिमवास्टैटिन",
    "ezetimibe": "एज़ेटिमाइब",
    "aspirin": "एस्पिरिन",
    "clopidogrel": "क्लोपिडोग्रेल",
    "ticagrelor": "टिकैग्रेलोर",
    "warfarin": "वारफेरिन",
    "apixaban": "एपिक्साबैन",
    "rivaroxaban": "रिवारोक्साबैन",
    "heparin": "हेपेरिन",
    "enoxaparin": "एनोक्सापेरिन",
    "salbutamol": "साल्बुटामोल",
    "albuterol": "अल्बुटेरोल",
    "formoterol": "फॉर्मोटेरोल",
    "salmeterol": "सैल्मेटेरोल",
    "budesonide": "बुडेसोनाइड",
    "fluticasone": "फ्लूटिकासोन",
    "tiotropium": "टायोट्रोपियम",
    "ipratropium": "इप्रैट्रोपियम",
    "montelukast": "मोंटेलुकास्ट",
    "theophylline": "थियोफिलिन",
    "prednisone": "प्रेडनिसोन",
    "prednisolone": "प्रेडनिसोलोन",
    "corticosteroid": "कॉर्टिकोस्टेरॉइड",
    "corticosteroids": "कॉर्टिकोस्टेरॉइड",
    "omalizumab": "ओमालिज़ुमाब",
    "mepolizumab": "मेपोलिज़ुमाब",
    "dupilumab": "ड्यूपिलुमाब",
    "omeprazole": "ओमेप्राज़ोल",
    "pantoprazole": "पैंटोप्राज़ोल",
    "esomeprazole": "एसोमेप्राज़ोल",
    "ranitidine": "रैनिटिडिन",
    "domperidone": "डोम्पेरिडोन",
    "ondansetron": "ओनडैंसेट्रोन",
    "mesalamine": "मेसालामाइन",
    "sulfasalazine": "सल्फ़ासालाज़ीन",
    "azathioprine": "अज़ाथायोप्रीन",
    "mycophenolate": "माइकोफेनोलेट",
    "tacrolimus": "टैक्रोलिमस",
    "cyclosporine": "साइक्लोस्पोरिन",
    "rituximab": "रिटुक्सिमाब",
    "trastuzumab": "ट्रैस्टुज़ुमाब",
    "bevacizumab": "बेवासिज़ुमाब",
    "pembrolizumab": "पेम्ब्रोलिज़ुमाब",
    "nivolumab": "निवोलूमाब",
    "imatinib": "इमैटिनिब",
    "gefitinib": "गेफ़िटिनिब",
    "erlotinib": "एरलोटिनिब",
    "osimertinib": "ओसिमर्टिनिब",
    "sorafenib": "सोराफ़ेनिब",
    "sunitinib": "सुनितिनिब",
    "lenvatinib": "लेनवैटिनिब",
    "tamoxifen": "टैमोक्सिफ़ेन",
    "letrozole": "लेट्रोज़ोल",
    "anastrozole": "एनास्ट्रोज़ोल",
    "cisplatin": "सिस्प्लैटिन",
    "carboplatin": "कार्बोप्लैटिन",
    "paclitaxel": "पैक्लिटैक्सल",
    "docetaxel": "डोसेटैक्सल",
    "doxorubicin": "डॉक्सोरूबिसिन",
    "cyclophosphamide": "साइक्लोफॉस्फामाइड",
    "gemcitabine": "जेमसिटाबीन",
    "capecitabine": "कैपेसिटाबीन",
    "lenalidomide": "लेनैलिडोमाइड",
    "thalidomide": "थैलिडोमाइड",
    "bortezomib": "बोर्टेज़ोमिब",
    "daratumumab": "डाराटुमुमाब",
    "hydroxyurea": "हाइड्रॉक्सीयूरिया",
    "deferasirox": "डिफेरासिरोक्स",
    "gabapentin": "गैबापेंटिन",
    "pregabalin": "प्रीगैबालिन",
    "duloxetine": "डुलोक्सेटिन",
    "amitriptyline": "अमिट्रिप्टीलीन",
    "sertraline": "सर्ट्रालीन",
    "fluoxetine": "फ्लुऑक्सेटीन",
    "escitalopram": "एस्सिटालोप्राम",
    "venlafaxine": "वेनलाफैक्सीन",
    "mirtazapine": "मिर्टाज़ापीन",
    "alprazolam": "अल्प्राज़ोलम",
    "clonazepam": "क्लोनाज़ेपाम",
    "risperidone": "रिस्पेरिडोन",
    "olanzapine": "ओलैंज़ापीन",
    "quetiapine": "क्वेटियापीन",
    "levodopa": "लेवोडोपा",
    "pramipexole": "प्रामिपेक्सोल",
    "donepezil": "डोनेपेज़िल",
    "memantine": "मेमैंटीन",
    "allopurinol": "अलोपुरिनॉल",
    "febuxostat": "फेबुक्सोस्टैट",
    "colchicine": "कोल्चिसीन",
    "ibuprofen": "इबुप्रोफ़ेन",
    "diclofenac": "डाइक्लोफिनैक",
    "aceclofenac": "एसिक्लोफिनैक",
    "paracetamol": "पैरासिटामोल",
    "tramadol": "ट्रामाडोल",
    "morphine": "मॉर्फिन",
    "finasteride": "फिनास्टेराइड",
    "tamsulosin": "टैमसुलोसिन",
    "sildenafil": "सिल्डेनाफ़िल",
    "tadalafil": "टैडलाफ़िल",
    "alendronate": "एलेंड्रोनेट",
    "denosumab": "डेनोसुमाब",
    "levothyroxine": "लेवोथायरॉक्सिन",
    "glipizide": "ग्लिपिज़ाइड",
    "gliclazide": "ग्लिक्लाज़ाइड",
    "metronidazole": "मेट्रोनिडाज़ोल",
    "fluconazole": "फ्लूकोनाज़ोल",
    "azithromycin": "एज़िथ्रोमायसिन",
    "amoxicillin": "अमोक्सिसिलिन",
    "ciprofloxacin": "सिप्रोफ्लॉक्सासिन",
    "levofloxacin": "लेवोफ्लॉक्सासिन",
    "doxycycline": "डॉक्सीसाइक्लिन",
    "ceftriaxone": "सेफ्ट्रायाक्सोन",
    "acyclovir": "एसाइक्लोविर",
    "oseltamivir": "ओसेल्टामिविर",
    "tenofovir": "टेनोफोविर",
    "lamivudine": "लैमिवुडीन",
    "entecavir": "एंटेकाविर",
    "sofosbuvir": "सोफोस्बुवीर",
}

# ---------------------------------------------------------------------------
# 3) Single words
# ---------------------------------------------------------------------------

_WORDS: dict[str, str] = {
    # glue (kept minimal - anything unmapped passes through as Hinglish)
    "and": "और", "or": "या", "not": "नहीं", "never": "कभी नहीं",
    "is": "है", "are": "हैं", "was": "था", "were": "थे", "be": "हो",
    "been": "हो चुका", "being": "हो रहा", "will": "होगा", "would": "होगा",
    "should": "चाहिए", "must": "अवश्य", "may": "सकता है", "can": "सकते हैं",
    "cannot": "नहीं कर सकते", "a": "एक", "an": "एक", "any": "कोई भी",
    "all": "सभी", "both": "दोनों", "each": "प्रत्येक", "every": "हर",
    "more": "अधिक", "most": "सबसे अधिक", "less": "कम", "few": "कुछ",
    "several": "कई", "also": "भी", "only": "केवल", "other": "अन्य",
    "others": "अन्य", "such": "ऐसे", "then": "तब", "when": "जब",
    "where": "जहां", "while": "जबकि", "during": "के दौरान",
    "despite": "के बावजूद", "unless": "जब तक नहीं", "until": "जब तक",
    "before": "पहले", "after": "बाद", "per": "प्रति", "either": "कोई भी",
    "neither": "कोई नहीं", "including": "सहित", "include": "शामिल",
    "includes": "शामिल", "included": "शामिल", "except": "छोड़कर",
    "because": "क्योंकि", "but": "लेकिन", "however": "हालांकि",
    "one": "एक", "two": "दो", "three": "तीन", "four": "चार", "five": "पांच",
    "six": "छह", "seven": "सात", "eight": "आठ", "nine": "नौ", "ten": "दस",
    "half": "आधा", "twice": "दो बार", "thrice": "तीन बार", "once": "एक बार",
    "first": "पहला", "second": "दूसरा", "third": "तीसरा", "type": "टाइप",
    "type-2": "टाइप-2", "type-1": "टाइप-1", "type-3": "टाइप-3",
    # people
    "patient": "मरीज़", "patients": "मरीज़", "participant": "प्रतिभागी",
    "participants": "प्रतिभागी", "subject": "प्रतिभागी", "subjects": "प्रतिभागी",
    "adult": "वयस्क", "adults": "वयस्क", "male": "पुरुष", "males": "पुरुष",
    "female": "महिला", "females": "महिला", "man": "पुरुष", "men": "पुरुष",
    "woman": "महिला", "women": "महिलाएं", "child": "बच्चा", "children": "बच्चे",
    "adolescent": "किशोर", "volunteer": "स्वयंसेवक", "volunteers": "स्वयंसेवक",
    "people": "लोग", "person": "व्यक्ति", "individual": "व्यक्ति",
    "individuals": "व्यक्ति", "investigator": "अन्वेषक", "investigators": "अन्वेषक",
    "sponsor": "प्रायोजक", "site": "साइट", "sites": "साइट",
    "center": "केंद्र", "centers": "केंद्र", "centre": "केंद्र", "centres": "केंद्र",
    "hospital": "अस्पताल", "hospitals": "अस्पताल", "doctor": "डॉक्टर",
    "physician": "चिकित्सक", "physicians": "चिकित्सक", "nurse": "नर्स",
    "gender": "लिंग", "sex": "लिंग", "age": "उम्र", "aged": "आयु",
    # time
    "year": "वर्ष", "years": "वर्ष", "month": "महीना", "months": "महीने",
    "week": "सप्ताह", "weeks": "सप्ताह", "day": "दिन", "days": "दिन",
    "hour": "घंटा", "hours": "घंटे", "minute": "मिनट", "minutes": "मिनट",
    "time": "समय", "period": "अवधि", "duration": "अवधि", "past": "पिछले",
    "last": "पिछले", "previous": "पिछला", "previously": "पहले",
    "prior": "पूर्व", "ago": "पहले", "current": "वर्तमान", "currently": "अभी",
    "ongoing": "जारी", "recent": "हाल का", "recently": "हाल ही में",
    "new": "नया", "newly": "नए", "history": "इतिहास", "historical": "पुराना",
    "early": "प्रारंभिक", "late": "देर का", "daily": "रोज़",
    "weekly": "साप्ताहिक", "monthly": "मासिक", "long-term": "दीर्घकालिक",
    "short-term": "अल्पकालिक", "baseline": "बेसलाइन", "follow-up": "फॉलो-अप",
    "follow": "फॉलो", "visit": "विज़िट", "visits": "विज़िट",
    "minimum": "न्यूनतम", "maximum": "अधिकतम", "limit": "सीमा",
    "limits": "सीमा", "range": "सीमा", "ranges": "सीमा", "upper": "ऊपरी",
    "lower": "निचला", "interval": "अंतराल", "window": "अवधि",
    # body / clinical nouns
    "disease": "बीमारी", "diseases": "बीमारी", "disorder": "विकार",
    "disorders": "विकार", "condition": "बीमारी", "conditions": "बीमारी",
    "syndrome": "सिंड्रोम", "syndromes": "सिंड्रोम", "symptom": "लक्षण",
    "symptoms": "लक्षण", "diagnosis": "निदान", "diagnoses": "निदान",
    "diagnosed": "निदान", "diagnostic": "नैदानिक", "therapy": "थेरेपी",
    "therapies": "थेरेपी", "therapeutic": "चिकित्सकीय",
    "treatment": "इलाज", "treatments": "इलाज", "treat": "इलाज",
    "treated": "इलाज", "treating": "इलाज", "medication": "दवा",
    "medications": "दवाएं", "medicine": "दवा", "medicines": "दवाएं",
    "drug": "दवा", "drugs": "दवाएं", "agent": "एजेंट", "agents": "एजेंट",
    "dose": "खुराक", "doses": "खुराक", "dosing": "खुराक", "dosage": "खुराक",
    "regimen": "खुराक योजना", "regimens": "खुराक योजना", "naive": "नेइव (पहले इलाज नहीं)",
    "exposure": "सेवन", "washout": "वॉशआउट", "titration": "टाइट्रेशन",
    "concomitant": "साथ की", "concurrent": "साथ की", "combination": "संयोजन",
    "monotherapy": "एकल थेरेपी", "adjunct": "सहायक", "rescue": "रेस्क्यू",
    "fixed": "निश्चित", "add-on": "ऐड-ऑन", "placebo": "प्लेसीबो",
    "vaccine": "टीका", "vaccines": "टीका", "inhibitor": "इनहिबिटर",
    "inhibitors": "इनहिबिटर", "agonist": "एगोनिस्ट", "antagonist": "एंटागोनिस्ट",
    "antibody": "एंटीबॉडी", "antibodies": "एंटीबॉडी", "monoclonal": "मोनोक्लोनल",
    "targeted": "लक्षित", "novel": "नई", "gene": "जीन", "genetic": "आनुवंशिक",
    "cell": "कोशिका", "cells": "कोशिका", "cellular": "कोशिकीय",
    "receptor": "रिसेप्टर", "receptors": "रिसेप्टर", "protein": "प्रोटीन",
    "enzyme": "एंज़ाइम", "hormone": "हार्मोन", "vitamin": "विटामिन",
    "supplement": "पूरक", "transplant": "प्रत्यारोपण", "transplantation": "प्रत्यारोपण",
    "transfusion": "रक्तचढ़ाना", "transfusions": "रक्तचढ़ाना", "dialysis": "डायलिसिस",
    "biopsy": "बायोप्सी", "imaging": "इमेजिंग", "scan": "स्कैन", "scans": "स्कैन",
    "ultrasound": "अल्ट्रासाउंड", "surgery": "सर्जरी", "surgical": "सर्जिकल",
    "procedure": "प्रक्रिया", "procedures": "प्रक्रिया", "device": "डिवाइस",
    "devices": "डिवाइस", "catheter": "कैथेटर", "stent": "स्टेंट",
    # labs / measures
    "blood": "रक्त", "serum": "सीरम", "plasma": "प्लाज़्मा", "urine": "मूत्र",
    "urinary": "मूत्र", "hemoglobin": "हीमोग्लोबिन", "haemoglobin": "हीमोग्लोबिन",
    "platelet": "प्लेटलेट", "platelets": "प्लेटलेट", "creatinine": "क्रिएटिनिन",
    "glucose": "ग्लूकोज", "glycemic": "ग्लाइसेमिक", "glycaemic": "ग्लाइसेमिक",
    "cholesterol": "कोलेस्ट्रॉल", "triglyceride": "ट्राइग्लिसराइड",
    "triglycerides": "ट्राइग्लिसराइड", "lipid": "लिपिड", "lipids": "लिपिड",
    "bilirubin": "बिलीरुबिन", "albumin": "एल्ब्यूमिन", "potassium": "पोटैशियम",
    "sodium": "सोडियम", "calcium": "कैल्शियम", "iron": "आयरन",
    "ferritin": "फेरिटिन", "insulin-like": "इंसुलिन जैसा", "value": "मान",
    "values": "मान", "level": "स्तर", "levels": "स्तर", "count": "गिनती",
    "counts": "गिनती", "rate": "दर", "rates": "दर", "ratio": "अनुपात",
    "percent": "प्रतिशत", "percentage": "प्रतिशत", "predicted": "अनुमानित",
    "fraction": "फ्रैक्शन", "ejection": "इजेक्शन", "systolic": "सिस्टोलिक",
    "diastolic": "डायस्टोलिक", "pressure": "प्रेशर", "weight": "वजन",
    "height": "कद", "mass": "मास", "index": "इंडेक्स", "scale": "स्केल",
    "score": "स्कोर", "scores": "स्कोर", "test": "टेस्ट", "tests": "टेस्ट",
    "testing": "टेस्टिंग", "laboratory": "प्रयोगशाला", "local": "स्थानीय",
    # symptoms
    "pain": "दर्द", "painful": "दर्दनाक", "fever": "बुखार", "cough": "खांसी",
    "breath": "सांस", "breathing": "सांस", "dyspnea": "सांस फूलना",
    "wheezing": "सांस में सीटी", "sputum": "बलगम", "fatigue": "थकान",
    "weakness": "कमजोरी", "dizziness": "चक्कर", "headache": "सिरदर्द",
    "nausea": "जी मिचलाना", "vomiting": "उल्टी", "diarrhea": "दस्त",
    "constipation": "कब्ज", "swelling": "सूजन", "edema": "सूजन",
    "itching": "खुजली", "rash": "रैश", "bleeding": "रक्तस्राव",
    "palpitations": "धड़कन", "chest": "छाती", "thirst": "प्यास",
    "urination": "पेशाब", "numbness": "सुन्नपन", "insomnia": "नींद की समस्या",
    "anxiety": "चिंता", "depression": "अवसाद", "seizure": "दौरे",
    "syncope": "बेहोशी", "appetite": "भूख", "loss": "कमी", "gain": "वृद्धि",
    "malaise": "बीमारी जैसा अहसास", "sweating": "पसीना", "cramps": "मरोड़",
    "stiffness": "अकड़न", "joint": "जोड़", "joints": "जोड़", "back": "पीठ",
    "neck": "गर्दन", "knee": "घुटना", "hip": "कूल्हा", "shoulder": "कंधा",
    # states / adjectives
    "severe": "गंभीर", "moderate": "मध्यम", "mild": "हल्का", "stable": "स्थिर",
    "unstable": "अस्थिर", "uncontrolled": "अनियंत्रित", "controlled": "नियंत्रित",
    "active": "सक्रिय", "inactive": "निष्क्रिय", "recurrent": "आवर्ती",
    "refractory": "प्रतिरोधी", "resistant": "प्रतिरोधी", "symptomatic": "लक्षण वाला",
    "asymptomatic": "लक्षणहीन", "significant": "महत्वपूर्ण", "adequate": "पर्याप्त",
    "inadequate": "अपर्याप्त", "insufficient": "अपर्याप्त", "sufficient": "पर्याप्त",
    "positive": "सकारात्मक", "negative": "नकारात्मक", "acute": "तीव्र",
    "chronic": "पुरानी", "subacute": "उपतीव्र", "advanced": "उन्नत",
    "metastatic": "मेटास्टैटिक", "systemic": "सिस्टमिक", "primary": "प्राथमिक",
    "secondary": "द्वितीयक", "terminal": "अंतिम", "progressive": "बढ़ता हुआ",
    "worsening": "बिगड़ता", "improved": "सुधरा", "serious": "गंभीर",
    "fatal": "घातक", "benign": "सौम्य", "malignant": "घातक",
    "malignancy": "कैंसर", "inoperable": "अचिकित्सेय", "unresectable": "अनुच्छेद्य",
    "overweight": "अधिक वजन", "obese": "मोटापे", "obesity": "मोटापा",
    "healthy": "स्वस्थ", "normal": "सामान्य", "abnormal": "असामान्य",
    "high": "उच्च", "low": "निम्न", "greater": "अधिक",
    "risk": "जोखिम", "beast": "स्तन",  # "Beast Cancer" typo in the demo dataset
    # diseases (single words)
    "cancer": "कैंसर", "carcinoma": "कैंसर", "tumor": "ट्यूमर",
    "tumour": "ट्यूमर", "tumors": "ट्यूमर", "tumours": "ट्यूमर",
    "neoplasm": "ट्यूमर", "neoplasms": "ट्यूमर", "leukemia": "ल्यूकीमिया",
    "leukaemia": "ल्यूकीमिया", "lymphoma": "लिंफोमा", "melanoma": "मेलानोमा",
    "hypertension": "उच्च रक्तचाप", "hypotension": "निम्न रक्तचाप",
    "diabetes": "मधुमेह", "diabetic": "मधुमेह", "prediabetes": "प्रीडायबिटीज",
    "nephropathy": "नेफ्रोपैथी", "retinopathy": "रेटिनोपैथी",
    "neuropathy": "न्यूरोपैथी", "kidney": "किडनी", "renal": "किडनी",
    "liver": "यकृत", "hepatic": "यकृत", "biliary": "पित्त",
    "cirrhosis": "सिरोसिस", "hepatitis": "हेपेटाइटिस",
    "steatohepatitis": "स्टीटोहेपेटाइटिस", "fibrosis": "फाइब्रोसिस",
    "jaundice": "पीलिया", "ascites": "जलसंचय", "varices": "वेराइसीज़",
    "heart": "हृदय", "cardiac": "हृदय", "cardiovascular": "हृदय-रक्तवाहिकी",
    "coronary": "कोरोनरी", "myocardial": "हृदय की मांसपेशी",
    "infarction": "रोध", "stroke": "स्ट्रोक", "angina": "एनजाइना",
    "arrhythmia": "अतालता", "atrial": "अलिंद", "fibrillation": "फिब्रिलेशन",
    "cardiomyopathy": "कार्डियोमायोपैथी", "bradycardia": "ब्रैडीकार्डिया",
    "atherosclerosis": "एथेरोस्क्लेरोसिस", "ventricular": "वेंट्रिकल",
    "asthma": "दमा", "copd": "सीओपीडी", "obstructive": "अवरोधक",
    "pulmonary": "फुफ्फुसीय", "respiratory": "श्वसन", "lung": "फेफड़े",
    "exacerbation": "बिगड़न (एक्सेर्बेशन)", "anemia": "एनीमिया",
    "anaemia": "एनीमिया", "thalassemia": "थैलेसीमिया", "myelofibrosis": "मायलोफाइब्रोसिस",
    "infection": "संक्रमण", "infections": "संक्रमण", "viral": "वायरल",
    "bacterial": "जीवाणु", "tuberculosis": "तपेदिक", "dengue": "डेंगू",
    "malaria": "मलेरिया", "typhoid": "टाइफाइड", "covid": "कोविड",
    "influenza": "इन्फ्लूएंज़ा", "pneumonia": "निमोनिया", "sepsis": "सेप्सिस",
    "candidiasis": "कैंडिडियासिस", "herpes": "हर्पीज़",
    "dermatitis": "डर्मेटाइटिस", "psoriasis": "सोरायसिस", "eczema": "एक्ज़िमा",
    "acne": "मुंहासे", "urticaria": "पित्ती", "arthritis": "गठिया",
    "rheumatoid": "रूमेटाइड", "osteoarthritis": "ऑस्टियोआर्थराइटिस",
    "lupus": "लूपस", "autoimmune": "ऑटोइम्यून", "gout": "गाउट",
    "osteoporosis": "ऑस्टियोपोरोसिस", "depressive": "अवसाद",
    "schizophrenia": "सिज़ोफ्रेनिया", "alzheimer": "अल्ज़ाइमर",
    "parkinson": "पार्किंसन", "epilepsy": "मिर्गी", "migraine": "माइग्रेन",
    "dementia": "डिमेंशिया", "endometriosis": "एंडोमेट्रियोसिस",
    "preeclampsia": "प्रीएक्लैंपसिया", "pregnancy": "गर्भावस्था",
    "pregnant": "गर्भवती", "breastfeeding": "स्तनपान", "lactating": "धात्री",
    "gestational": "गर्भकालीन", "fetal": "गर्भस्थ", "metabolic": "मेटाबॉलिक",
    "dysfunction": "डिसफंक्शन", "nash": "नैश", "mash": "मैश", "masld": "मैस्ल्ड",
    "glaucoma": "ग्लूकोमा", "ocular": "नेत्र", "eye": "आंख",
    "stomach": "पेट", "abdominal": "पेट", "gastric": "पेट", "colon": "कोलन",
    "pancreas": "अग्न्याशय", "prostate": "प्रोस्टेट", "ovarian": "अंडाशय",
    "breast": "स्तन", "bone": "हड्डी", "marrow": "मज्जा", "muscle": "मांसपेशी",
    "skin": "त्वचा", "brain": "मस्तिष्क", "nerve": "नस", "thyroid": "थायरॉइड",
    "hematologic": "रक्त संबंधी", "parasitic": "परजीवी",
    # actions / trial design
    "requires": "मांग करता है", "require": "मांग करता है",
    "required": "आवश्यक", "requirement": "आवश्यकता",
    "requirements": "आवश्यकताएं", "needed": "आवश्यक", "needs": "आवश्यकता",
    "satisfies": "को संतुष्ट करता", "satisfy": "संतुष्ट करता",
    "satisfied": "संतुष्ट", "satisfying": "संतुष्ट करते हुए",
    "match": "मेल", "matches": "से मेल", "matching": "से मेल",
    "conflict": "टकराव", "conflicts": "टकराव", "conflicting": "टकराव",
    "allowed": "अनुमत", "allow": "अनुमति", "allows": "अनुमति",
    "permitted": "अनुमत", "prohibited": "निषिद्ध", "forbidden": "निषिद्ध",
    "banned": "निषिद्ध", "restricted": "प्रतिबंधित", "restrict": "प्रतिबंधित",
    "accepts": "स्वीकार करता है", "accept": "स्वीकार", "accepted": "स्वीकार्य",
    "acceptable": "स्वीकार्य", "unacceptable": "अस्वीकार्य",
    "candidate": "उम्मीदवार", "screening": "स्क्रीनिंग", "screened": "स्क्रीन किया",
    "randomization": "रैंडमाइज़ेशन", "randomisation": "रैंडमाइज़ेशन",
    "randomized": "रैंडमाइज़्ड", "randomised": "रैंडमाइज़्ड",
    "stratified": "स्तरीकृत", "blinded": "ब्लाइंडेड", "masked": "ब्लाइंडेड",
    "single": "सिंगल", "double": "डबल", "blind": "ब्लाइंड", "open": "ओपन",
    "label": "लेबल", "parallel": "समानांतर", "group": "समूह", "groups": "समूह",
    "arm": "आर्म", "arms": "आर्म", "controlled-trial": "नियंत्रित ट्रायल",
    "versus": "बनाम", "vs": "बनाम", "trial": "ट्रायल", "trials": "ट्रायल",
    "study": "अध्ययन", "studies": "अध्ययन", "studying": "अध्ययन",
    "protocol": "प्रोटोकॉल", "phase": "चरण", "observational": "ऑब्ज़र्वेशनल",
    "interventional": "इंटरवेंशनल", "intervention": "इंटरवेंशन",
    "interventions": "इंटरवेंशन", "prospective": "प्रोस्पेक्टिव",
    "retrospective": "रेट्रोस्पेक्टिव", "cross": "क्रॉस", "cohort": "कोहोर्ट",
    "registry": "रजिस्ट्री", "survey": "सर्वे", "evaluation": "मूल्यांकन",
    "evaluate": "मूल्यांकन", "assess": "मूल्यांकन", "assessment": "मूल्यांकन",
    "assessed": "मूल्यांकित", "effect": "प्रभाव", "effects": "प्रभाव",
    "effective": "प्रभावी", "effectiveness": "प्रभावकारिता",
    "efficacy": "प्रभावकारिता", "safety": "सुरक्षा", "safe": "सुरक्षित",
    "tolerability": "सहनशीलता", "adverse": "प्रतिकूल", "event": "घटना",
    "events": "घटनाएं", "outcome": "परिणाम", "outcomes": "परिणाम",
    "endpoint": "एंडपॉइंट", "endpoints": "एंडपॉइंट", "measure": "माप",
    "measures": "माप", "measured": "मापा", "measurement": "माप",
    "change": "बदलाव", "changes": "बदलाव", "improvement": "सुधार",
    "improve": "सुधार", "response": "प्रतिक्रिया", "remission": "रिमिशन",
    "relapse": "रिलैप्स", "recurrence": "पुनरावृत्ति", "progression": "प्रगति",
    "progression-free": "प्रगति-मुक्त", "survival": "जीवनकाल",
    "mortality": "मृत्युदर", "death": "मृत्यु",
    "hospitalization": "अस्पताल भर्ती", "hospitalisation": "अस्पताल भर्ती",
    "schedule": "शेड्यूल", "scheduled": "निर्धारित", "planned": "नियोजित",
    "plan": "योजना", "planning": "योजना", "consent": "सहमति",
    "consenting": "सहमति देने", "informed": "सूचित", "signed": "हस्ताक्षरित",
    "signing": "हस्ताक्षर करने", "written": "लिखित", "willing": "इच्छुक",
    "willingness": "इच्छा", "able": "सक्षम", "unable": "असमर्थ",
    "comply": "पालन", "compliance": "अनुपालन", "adherence": "पालन",
    "participate": "भाग लेना", "participation": "भागीदारी",
    "participating": "भाग ले रहे", "enrolled": "नामांकित",
    "enrollment": "नामांकन", "eligible": "पात्र", "ineligible": "अपात्र",
    "eligibility": "पात्रता", "excluded": "अपवर्जित", "excludes": "अपवर्जित करता है",
    "excluding": "को छोड़कर", "exclusion": "अपवर्जन", "exclusions": "अपवर्जन",
    "applies": "लागू", "apply": "लागू", "targets": "लक्षित करता है",
    "target": "लक्ष्य", "confirmed": "पुष्ट", "confirm": "पुष्ट करना",
    "confirmation": "पुष्टि", "documented": "प्रलेखित", "recorded": "दर्ज",
    "records": "रिकॉर्ड", "record": "रिकॉर्ड", "verified": "सत्यापित",
    "verification": "सत्यापन", "received": "प्राप्त", "receive": "प्राप्त",
    "receiving": "प्राप्त कर रहे", "given": "दिया", "administered": "दी",
    "taking": "ले रहे", "takes": "लेते", "take": "लेना", "taking-": "ले रहे",
    "used": "इस्तेमाल", "use": "इस्तेमाल", "using": "इस्तेमाल करते",
    "usage": "इस्तेमाल", "useful": "उपयोगी", "shows": "दिखाता है",
    "show": "दिखाता है", "indicates": "संकेत देता है", "seek": "तलाश",
    "seeks": "तलाश करता है", "exceeds": "से अधिक है", "supply": "प्रदान",
    "available": "उपलब्ध", "unavailable": "अनुपलब्ध", "unknown": "अज्ञात",
    "known": "ज्ञात", "potential": "संभावित", "key": "मुख्य",
    "important": "महत्वपूर्ण", "clinical": "क्लिनिकल", "clinically": "क्लिनिकल रूप से",
    "medical": "चिकित्सा", "treatment-naive": "ट्रीटमेंट-नेइव",
    "treatment-naïve": "ट्रीटमेंट-नेइव", "evidence": "प्रमाण",
    "according": "के अनुसार", "guidelines": "दिशानिर्देश",
    "international": "अंतर्राष्ट्रीय", "national": "राष्ट्रीय",
    "india": "भारत", "indian": "भारतीय", "urban": "शहरी", "rural": "ग्रामीण",
    "variability": "परिवर्तनशीलता", "monitoring": "निगरानी",
    "continuous": "निरंतर", "management": "प्रबंधन", "prevention": "रोकथाम",
    "association": "संबंध", "associated": "से जुड़ा", "specialist": "विशेषज्ञ",
    "opinion": "राय", "judgment": "निर्णय", "judgement": "निर्णय",
    "investigational": "अन्वेषणात्मक", "experimental": "प्रयोगात्मक",
    "standard": "मानक", "routine": "नियमित", "care": "देखभाल",
    "practice": "अभ्यास", "physician's": "चिकित्सक",
    "qualify": "योग्य", "qualified": "योग्य",
    "status": "स्थिति", "this": "यह", "does": "करता",
    "studies": "अध्ययन करता है",
    "comparison": "तुलना", "bioequivalence": "बायोइक्विवलेंस",
    "generic": "जेनेरिक", "inhaled": "इनहेल्ड", "inadequately": "अपर्याप्त रूप से",
    "prevalence": "प्रसरण", "among": "बीच", "attending": "आने वाले",
    "antenatal": "प्रसूति-पूर्व", "clinic": "क्लिनिक", "clinics": "क्लिनिक",
    "tablet": "टैबलेट", "tablets": "टैबलेट", "capsule": "कैप्सूल",
    "injection": "इंजेक्शन", "yoga": "योग", "control": "नियंत्रण",
    "adalimumab": "एडालिमुमाब", "biosimilar": "बायोसिमिलर",
    "adequate": "पर्याप्त", "history-": "इतिहास",
}

# ---------------------------------------------------------------------------
# Compiled phrase patterns (longest first; hyphen == space, case-insensitive)
# ---------------------------------------------------------------------------

def _phrase_pattern(en: str) -> re.Pattern:
    words = [re.escape(w) for w in en.split()]
    return re.compile(r"(?<![A-Za-z])" + r"[\s-]+".join(words) + r"(?![A-Za-z])", re.I)


_PHRASE_RES: list[tuple[re.Pattern, str]] = [
    (_phrase_pattern(en), hi)
    for en, hi in sorted(_PHRASES.items(), key=lambda kv: -len(kv[0]))
]

# Token = letters/digits/% . / - ' (covers "HbA1c", "mg/dL", "7.5", "add-on",
# "180/110") - everything else (punctuation, spaces) is preserved as-is.
_TOKEN_RE = re.compile(r"[\w%./'’-]+", re.UNICODE)


def _word_repl(m: "re.Match") -> str:
    return _WORDS.get(m.group(0).lower(), m.group(0))


@lru_cache(maxsize=8192)
def _translate_cached(text: str) -> str:
    out = text

    # 1) sentence-shape templates
    for pat, repl in _TEMPLATES:
        out = pat.sub(repl, out)

    # 2) multi-word phrases, longest first
    for pat, hi in _PHRASE_RES:
        if pat.search(out):
            out = pat.sub(hi, out)

    # 3) single words - unknown tokens survive untouched
    out = _TOKEN_RE.sub(_word_repl, out)

    # 4) tidy spacing around punctuation introduced by the passes
    out = re.sub(r"\s*\(\s*s\s*\)", "", out)   # "2 year(s) ago" -> "2 वर्ष पहले"
    out = re.sub(r'\s+"', '"', out)
    out = re.sub(r"\s+([,.;:%])", r"\1", out)
    out = re.sub(r"([,.;:])(?=[^\s\d])", r"\1 ", out)
    out = re.sub(r"\(\s+", "(", out)
    out = re.sub(r"\s+\)", ")", out)
    out = re.sub(r"\s{2,}", " ", out)
    return out.strip()


def to_hindi(text) -> str | None:
    """Best-effort offline English→Hindi rendering of trial-domain text.

    Medical content is mapped through the glossary; numbers, units,
    abbreviations and unmapped words pass through (clinical Hinglish).
    Returns None for None/empty input so callers can fall back cleanly.
    """
    if text is None:
        return None
    text = str(text).strip()
    if not text or not any(ch.isalpha() for ch in text):
        return text or None
    return _translate_cached(text)


def to_hindi_list(items) -> list[str] | None:
    """Translate a list of criterion/reason strings (None-safe)."""
    if items is None:
        return None
    return [to_hindi(x) or (x or "") for x in items]
